server:
  port: 9020
management:
  server:
    port: 9021
    endpoint:
      shutdown:
        enabled: true
spring:
  application:
    name: AngularApp
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
#  security:
#    user:
#      name: Jan
#      password: password
logging:
  level:
    root:
      #debug
jwt:
  signing:
    key:
      secret: mySecret
  get:
    token:
      uri: /authenticate
  refresh:
    token:
      uri: /refresh
  http:
    request:
      header: Authorization
  token:
    expiration:
      in:
        seconds: 604800